version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00" # KST 02:00
    groups:
      all-minor-patch-updates:
        patterns:
          - "*"
