FROM node:24

WORKDIR /app

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
    && echo "Asia/Seoul" > /etc/timezone
    
ENV NODE_OPTIONS="--max-old-space-size=4096" 

COPY package.json package-lock.json ./

RUN npm ci

RUN npx playwright install --with-deps

COPY . .

RUN npx prettier --write . || true

# Build arguments from GitHub Actions
ARG NEXT_PUBLIC_R2_URI
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_API_RUST_URL
ARG NEXT_PUBLIC_API_GO_URL
ARG NEXT_PUBLIC_API_HASKELL_URL
ARG NEXT_PUBLIC_API_AUTH_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_ADMIN_EMAILS
ARG NEXT_PUBLIC_UPLOAD_BASE_URL
ARG NEXT_PUBLIC_HACKERNEWS_API_KEY
ARG DISCORD_BOT_TOKEN
ARG DISCORD_USER_ID
ARG OSM_TILE_HOME_SERVER_URL
ARG NEXT_PUBLIC_OSM_PROVIDER_TILE_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN

# Set build-time environment variables
ENV NEXT_PUBLIC_R2_URI=$NEXT_PUBLIC_R2_URI
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_API_RUST_URL=$NEXT_PUBLIC_API_RUST_URL
ENV NEXT_PUBLIC_API_GO_URL=$NEXT_PUBLIC_API_GO_URL
ENV NEXT_PUBLIC_API_HASKELL_URL=$NEXT_PUBLIC_API_HASKELL_URL
ENV NEXT_PUBLIC_API_AUTH_URL=$NEXT_PUBLIC_API_AUTH_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_ADMIN_EMAILS=$NEXT_PUBLIC_ADMIN_EMAILS
ENV NEXT_PUBLIC_UPLOAD_BASE_URL=$NEXT_PUBLIC_UPLOAD_BASE_URL
ENV NEXT_PUBLIC_HACKERNEWS_API_KEY=$NEXT_PUBLIC_HACKERNEWS_API_KEY
ENV DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
ENV DISCORD_USER_ID=$DISCORD_USER_ID
ENV OSM_TILE_HOME_SERVER_URL=$OSM_TILE_HOME_SERVER_URL
ENV NEXT_PUBLIC_OSM_PROVIDER_TILE_URL=$NEXT_PUBLIC_OSM_PROVIDER_TILE_URL
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]