FROM node:24

WORKDIR /app

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
    && echo "Asia/Seoul" > /etc/timezone
    
ENV NODE_OPTIONS="--max-old-space-size=4096" 

COPY package.json package-lock.json ./

RUN npm ci

RUN npx playwright install --with-deps

COPY . .

RUN npx prettier --write . || true

# Build arguments from GitHub Actions
ARG NEXT_PUBLIC_R2_URI
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_REDIRECT_URI
ARG NEXT_PUBLIC_GITHUB_CLIENT_ID
ARG NEXT_PUBLIC_GITHUB_REDIRECT_URI
ARG NEXT_PUBLIC_API_RUST_URL
ARG NEXT_PUBLIC_AUTH_API_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_ADMIN_EMAILS
ARG NEXT_PUBLIC_UPLOAD_BASE_URL
ARG NEXT_PUBLIC_HACKERNEWS_API_KEY
ARG DISCORD_BOT_TOKEN
ARG DISCORD_USER_ID

# Set build-time environment variables
ENV NEXT_PUBLIC_R2_URI=$NEXT_PUBLIC_R2_URI
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_REDIRECT_URI=$NEXT_PUBLIC_GOOGLE_REDIRECT_URI
ENV NEXT_PUBLIC_GITHUB_CLIENT_ID=$NEXT_PUBLIC_GITHUB_CLIENT_ID
ENV NEXT_PUBLIC_GITHUB_REDIRECT_URI=$NEXT_PUBLIC_GITHUB_REDIRECT_URI
ENV NEXT_PUBLIC_API_RUST_URL=$NEXT_PUBLIC_API_RUST_URL
ENV NEXT_PUBLIC_AUTH_API_URL=$NEXT_PUBLIC_AUTH_API_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_ADMIN_EMAILS=$NEXT_PUBLIC_ADMIN_EMAILS
ENV NEXT_PUBLIC_UPLOAD_BASE_URL=$NEXT_PUBLIC_UPLOAD_BASE_URL
ENV NEXT_PUBLIC_HACKERNEWS_API_KEY=$NEXT_PUBLIC_HACKERNEWS_API_KEY
ENV DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
ENV DISCORD_USER_ID=$DISCORD_USER_ID

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]