name: "Dependabot Auto Merge"

permissions:
  contents: write 
  pull-requests: write 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          
      - name: Setup .env for CI
        run: cp .env.ci .env

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Enable auto-merge for Dependabot PRs
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
        if: success()
