name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key file
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/ci-key.pem
          chmod 600 /tmp/ci-key.pem

      - name: Clean up contents folder on EC2
        run: |
          ssh -i /tmp/ci-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} "
            cd /home/ubuntu/app/blog
            rm -rf contents/
          "

      - name: Rsync source code to EC2
        run: |
          echo "==== [Step 1] 현재 위치 : $(pwd) ===="
          ls -al
          echo "==== [Step 2] Rsync 실행 ===="
          rsync -avz --exclude='.git' --exclude='node_modules' --exclude='dist' --exclude='.env' -e "ssh -i /tmp/ci-key.pem -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/app/blog
          echo "==== [Step 3] Rsync 완료 ===="

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          directory: .
          inventory: |
            [web]
            ec2-instance ansible_host=${{ secrets.AWS_EC2_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/ci-key.pem
