name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ci-key.pem
          chmod 600 /tmp/ci-key.pem

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          directory: .
          inventory: |
            [web]
            ec2-instance ansible_host=${{ secrets.HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/ci-key.pem
