name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies and format code
        run: |
          npm ci
          npx prettier --write .
          npx eslint . --fix --ext .js,.ts,.tsx || true

      - name: Create SSH key file
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/ci-key.pem
          chmod 600 /tmp/ci-key.pem

      - name: Clean up contents folder on EC2
        run: |
          ssh -i /tmp/ci-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} "
            cd /home/ubuntu/app/blog
            rm -rf contents/
          "

      - name: Rsync source code to EC2
        run: |
          rsync -avz --delete --exclude='.git' --exclude='node_modules' --exclude='dist' --exclude='.env' -e "ssh -i /tmp/ci-key.pem -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/app/blog

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          directory: .
          inventory: |
            [web]
            ec2-instance ansible_host=${{ secrets.AWS_EC2_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/ci-key.pem

      - name: Sync posts metadata
        run: |
          RESPONSE=$(curl -s -X POST https://mogumogu.dev/api/posts/sync \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.HACKERNEWS_API_KEY }}")
          echo "$RESPONSE"

      - name: Check Google Indexing API quota
        id: indexing-quota
        run: |
          RESPONSE=$(curl -s https://mogumogu.dev/api/status/indexing \
            -H "Authorization: Bearer ${{ secrets.HACKERNEWS_API_KEY }}")
          echo "$RESPONSE"
          REMAINING=$(echo "$RESPONSE" | jq '.remaining')
          echo "remaining=$REMAINING" >> $GITHUB_OUTPUT

      - name: Google Indexing (batch)
        if: ${{ steps.indexing-quota.outputs.remaining > '198' }}
        run: |
          RESPONSE=$(curl -s -X POST https://mogumogu.dev/api/posts/indexing \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.HACKERNEWS_API_KEY }}")
          echo "$RESPONSE"