name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          inventory: |
            [web]
            ec2-instance ansible_host=${{ secrets.HOST }} ansible_user=ubuntu ansible_ssh_private_key="${{ secrets.SSH_KEY }}"
