name: Push to MongoDB

on:
  push:
    branches:
      - main

jobs:
  update_mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next.js API to upsert files to MongoDB
        run: curl -X POST https://mogumogu.dev/api/post/upsert
